apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "dYZpWx/Kw4KcMiU3yExYuZUwEnuEkUjsP6F3SGGaOTkUPl0WbM/4dCixTABat9Od\nrSap/fg1273y2kNxUv0nCbsZmtpZdRZ2yf7XApxATOWqwGb2Q8NgDCqANHJEjntw\nVVuV4Ku+ezYCCDQpDB8GISzzS7kwe1Lb3+Ega1WSSDU="
